# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Achievement(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, describe: str=None, goal: int=None):  # noqa: E501
        """Achievement - a model defined in Swagger

        :param id: The id of this Achievement.  # noqa: E501
        :type id: int
        :param name: The name of this Achievement.  # noqa: E501
        :type name: str
        :param describe: The describe of this Achievement.  # noqa: E501
        :type describe: str
        :param goal: The goal of this Achievement.  # noqa: E501
        :type goal: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'describe': str,
            'goal': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'describe': 'describe',
            'goal': 'goal'
        }

        self._id = id
        self._name = name
        self._describe = describe
        self._goal = goal

    @classmethod
    def from_dict(cls, dikt) -> 'Achievement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Achievement of this Achievement.  # noqa: E501
        :rtype: Achievement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Achievement.


        :return: The id of this Achievement.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Achievement.


        :param id: The id of this Achievement.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Achievement.


        :return: The name of this Achievement.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Achievement.


        :param name: The name of this Achievement.
        :type name: str
        """

        self._name = name

    @property
    def describe(self) -> str:
        """Gets the describe of this Achievement.


        :return: The describe of this Achievement.
        :rtype: str
        """
        return self._describe

    @describe.setter
    def describe(self, describe: str):
        """Sets the describe of this Achievement.


        :param describe: The describe of this Achievement.
        :type describe: str
        """

        self._describe = describe

    @property
    def goal(self) -> int:
        """Gets the goal of this Achievement.


        :return: The goal of this Achievement.
        :rtype: int
        """
        return self._goal

    @goal.setter
    def goal(self, goal: int):
        """Sets the goal of this Achievement.


        :param goal: The goal of this Achievement.
        :type goal: int
        """

        self._goal = goal
