# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, login: str=None, id_event: int=None):  # noqa: E501
        """Body1 - a model defined in Swagger

        :param login: The login of this Body1.  # noqa: E501
        :type login: str
        :param id_event: The id_event of this Body1.  # noqa: E501
        :type id_event: int
        """
        self.swagger_types = {
            'login': str,
            'id_event': int
        }

        self.attribute_map = {
            'login': 'login',
            'id_event': 'idEvent'
        }

        self._login = login
        self._id_event = id_event

    @classmethod
    def from_dict(cls, dikt) -> 'Body1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_1 of this Body1.  # noqa: E501
        :rtype: Body1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login(self) -> str:
        """Gets the login of this Body1.

        Логин пользователя  # noqa: E501

        :return: The login of this Body1.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login: str):
        """Sets the login of this Body1.

        Логин пользователя  # noqa: E501

        :param login: The login of this Body1.
        :type login: str
        """

        self._login = login

    @property
    def id_event(self) -> int:
        """Gets the id_event of this Body1.


        :return: The id_event of this Body1.
        :rtype: int
        """
        return self._id_event

    @id_event.setter
    def id_event(self, id_event: int):
        """Sets the id_event of this Body1.


        :param id_event: The id_event of this Body1.
        :type id_event: int
        """

        self._id_event = id_event
