# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, text: str=None, author: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param text: The text of this Body.  # noqa: E501
        :type text: str
        :param author: The author of this Body.  # noqa: E501
        :type author: str
        """
        self.swagger_types = {
            'text': str,
            'author': str
        }

        self.attribute_map = {
            'text': 'text',
            'author': 'author'
        }

        self._text = text
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this Body.


        :return: The text of this Body.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Body.


        :param text: The text of this Body.
        :type text: str
        """

        self._text = text

    @property
    def author(self) -> str:
        """Gets the author of this Body.

        логин пользователя  # noqa: E501

        :return: The author of this Body.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Body.

        логин пользователя  # noqa: E501

        :param author: The author of this Body.
        :type author: str
        """

        self._author = author
